version: '3.8'

services:
  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

  vue:
    build: ./frontend
    platform: linux/amd64
    container_name: vue
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development